import{a as d,S as h,i as u}from"./assets/vendor-80c693af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const L="/goit-js-hw-11/assets/error-icon-7115e62e.svg";d.defaults.baseURL="https://pixabay.com/api/";const b="42556248-7d7b04b226b16d9af953a75af";async function f(s,r){const{data:a}=await d.get("",{params:{page:r,per_page:10,key:b,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"}});return a}const o={gallery:document.querySelector(".gallery"),formSubmit:document.querySelector(".form"),input:document.querySelector(".input-value"),section:document.querySelector("section"),loader:document.querySelector("div"),loadMoreButton:document.querySelector('[data-action="load-more"]')};function m(s){const r=s.map(({webformatURL:a,largeImageURL:n,tags:e,likes:t,views:l,comments:g,downloads:y})=>`<li class="gallery-item">
                    <a class="gallery-link" href="${n}">
                        <img class="gallery-image"
                            src="${a}"
                            alt="${e}" />
                    </a>
                    <ul class="list">
                        <li class="list-info">Likes<p class="info">${t}</p></li>
                        <li class="list-info">Views<p class="info">${l}</p></li>
                        <li class="list-info">Comments<p class="info">${g}</p></li>
                        <li class="list-info">Downloads<p class="info">${y}</p></li>
                    </ul>
                </li>`).join("");o.gallery.insertAdjacentHTML("beforeend",r)}const p=new h(".gallery a",{captionsData:"alt",captionDelay:250});let i,c;o.formSubmit.addEventListener("submit",S);async function S(s){if(s.preventDefault(),o.gallery.innerHTML="",o.loadMoreButton.classList.remove("load-more"),i=1,c=o.input.value.trim(),o.loadMoreButton.classList.add("is-close"),c===""){u.show({titleColor:"#fff",titleSize:"16px",message:"Please, enter your search query!!!",messageColor:"#fff",messageSize:"16px",position:"topRight",backgroundColor:"#59A10D",close:!1});return}o.loader.classList.add("loader");try{const r=await f(c,i);if(r.total===0){u.show({titleColor:"#fff",titleSize:"16px",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#fff",messageSize:"16px",iconUrl:L,position:"topRight",backgroundColor:"#ef4040",close:!0,maxWidth:"432px"}),o.loader.classList.remove("loader");return}m(r.hits),o.loader.classList.remove("loader"),p.refresh()}catch(r){console.log(r)}o.formSubmit.reset(),o.loadMoreButton.classList.remove("is-close")}o.loadMoreButton.addEventListener("click",v);async function v(){i+=1,o.loader.classList.add("loader");try{const s=await f(c,i);if(m(s.hits),window.scrollBy({top:172*3+24*2+20*2,behavior:"smooth"}),p.refresh(),Math.ceil(s.totalHits/15)===i)return o.loadMoreButton.classList.add("is-close"),o.loader.classList.remove("loader"),u.error({icon:"",color:"blue",position:"topRight",message:"We're sorry, but you've reached the end of search results."})}catch(s){console.log(s)}o.loader.classList.remove("loader")}
//# sourceMappingURL=commonHelpers.js.map
